theme: jekyll-theme-cayman

title: [FHIR-bridge test documentation]
# description: [Documentation of tests implemented with Robot Framework]

show_downloads: ["true"]

github:
  log_url: tests/log.html
  report_url: tests/report.html
  testdocs_url: tests/fhir-bridge-robot-testdocu.html
