version: '3'
services:
  ehrbase:
    image: ehrbaseorg/ehrbase:latest
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      AUTH_TYPE: BASIC
      AUTH_USER: ehrbase-user
      AUTH_PASSWORD: SuperSecretPassword
      SYSTEM_NAME: local.ehrbase.org
    restart: on-failure
  ehrdb:
    image: ehrbaseorg/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
  fhirdb:
    image: postgres:11.5-alpine
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: fhir_bridge
      POSTGRES_PASSWORD: fhir_bridge

networks:
  ehrbase-net: {}
