spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
logging:
  level:
    ca.uhn.fhir: info
    org.apache.camel: info
    org.ehrbase.fhirbridge: debug
    org.hibernate: info
    org.openehealth.ipf: info
    org.quartz: info
    org.springframework: info
    org.springframework.boot: info